name: 🚀 Deploy Laravel App via SFTP

on:
  push:
    branches:
      - backend_dev
      - staging
      - preprod
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          if [ "${GITHUB_REF_NAME}" == "backend_dev" ]; then
            echo "REMOTE_PATH=/home/eord0oj6j22n/public_html/dev.almysapp.com/alyms" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "staging" ]; then
            echo "REMOTE_PATH=/home/eord0oj6j22n/public_html/dev.almysapp.com/alyms2" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "preprod" ]; then
            echo "REMOTE_PATH=/home/eord0oj6j22n/public_html/dev.almysapp.com/alyms3" >> $GITHUB_ENV
          elif [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "REMOTE_PATH=/home/eord0oj6j22n/public_html/dev.almysapp.com/alyms4" >> $GITHUB_ENV
          fi

      - name: Deploy files via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.ALYMS_HOST }}
          username: ${{ secrets.ALYMS_USERNAME }}
          password: ${{ secrets.ALYMS_PASSWORD }}
          port: 22
          local_path: ./
          remote_path: ${{ env.REMOTE_PATH }}
          sftp_only: true

      - name: Run Laravel commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.ALYMS_HOST }}
          username: ${{ secrets.ALYMS_USERNAME }}
          password: ${{ secrets.ALYMS_PASSWORD }}
          port: 22
          script: |
            cd ${{ env.REMOTE_PATH }}
            /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
            php artisan migrate --force
            php artisan optimize:clear
            php artisan optimize
          use_insecure_cipher: true
